### ISSUE TITLE
Flash OTA from ESP32-Rhasspy-Satellite

### ISSUE THREAD

**Issue by WhiteSockedDancer** [gnumpi/esphome_matrixio#1]
I'm running my matrixvoice with ESP32-Rhasspy-Satellite with Rhasspy 2.5.
https://github.com/Romkabouter/ESP32-Rhasspy-Satellite
I'm also thinking about switching to Rhasspy 3 within HA since i'm already using HA and alot of esphome devices.

Do you think there is a way to flash the firmware over the air (OTA) somehow, since i don't have the old RPI anymore in use and would have to set it up again.

Even if that is not possible. Keep up your good work! I would love to try it out!

**Comment by gnumpi** [comment]
I am not familiar with ESP32-Rhasspy, but ESPHome does support flashing via OTA. **If both bootloaders are compatible** it should be simple as just adding the following to your configuration: 

```
ota:
  password: CURRENT_OTA_PASSWORD   

wifi:
  use_address: CURRENT_HOSTNAME_OF_MATRIX_VOICE.local
```
and then:

```
esphome upload CONFIG.yaml
```
